---
- name: Exchange Keys between servers
  become: yes
  become_user: woodfolk
  hosts: servers
  tasks:
#    - name: SSH KeyGen command
#      shell: > 
#        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
#        creates="~/.ssh/id_rsa"
#
    - name: Fetch the keyfile from one server to another
      fetch: 
        src: "~/.ssh/woodfolk.pub"
        dest: "buffer/{{ansible_hostname}}-woodfolk.pub"
        flat: yes

    - name: Copy the file from master to the destination
      copy:
        src: "buffer/{{item.dest}}-woodfolk.pub"
        dest: "/tmp/remote-woodfolk.pub"  
      when: "{{ item.dest != ansible_hostname }}"
      with_items: 
        - { dest: "{{groups['app'][1]}}"}
        - { dest: "{{groups['app'][0]}}"}

    - name: add the public key into Authorized_keys file to enable Key Auth
      shell: "cat /tmp/remote-woodfolk.pub >> ~/.ssh/authorized_keys"
      register: addtoauth
